// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package location

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LocationClient is the client API for Location service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationClient interface {
	SetUserLocation(ctx context.Context, in *SetUserLocationRequest, opts ...grpc.CallOption) (*SetUserLocationResponse, error)
	ListUsersInRadius(ctx context.Context, in *ListUsersInRadiusRequest, opts ...grpc.CallOption) (*ListUsersInRadiusResponse, error)
}

type locationClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationClient(cc grpc.ClientConnInterface) LocationClient {
	return &locationClient{cc}
}

func (c *locationClient) SetUserLocation(ctx context.Context, in *SetUserLocationRequest, opts ...grpc.CallOption) (*SetUserLocationResponse, error) {
	out := new(SetUserLocationResponse)
	err := c.cc.Invoke(ctx, "/proto.Location/SetUserLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) ListUsersInRadius(ctx context.Context, in *ListUsersInRadiusRequest, opts ...grpc.CallOption) (*ListUsersInRadiusResponse, error) {
	out := new(ListUsersInRadiusResponse)
	err := c.cc.Invoke(ctx, "/proto.Location/ListUsersInRadius", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServer is the server API for Location service.
// All implementations must embed UnimplementedLocationServer
// for forward compatibility
type LocationServer interface {
	SetUserLocation(context.Context, *SetUserLocationRequest) (*SetUserLocationResponse, error)
	ListUsersInRadius(context.Context, *ListUsersInRadiusRequest) (*ListUsersInRadiusResponse, error)
	mustEmbedUnimplementedLocationServer()
}

// UnimplementedLocationServer must be embedded to have forward compatible implementations.
type UnimplementedLocationServer struct {
}

func (UnimplementedLocationServer) SetUserLocation(context.Context, *SetUserLocationRequest) (*SetUserLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserLocation not implemented")
}
func (UnimplementedLocationServer) ListUsersInRadius(context.Context, *ListUsersInRadiusRequest) (*ListUsersInRadiusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsersInRadius not implemented")
}
func (UnimplementedLocationServer) mustEmbedUnimplementedLocationServer() {}

// UnsafeLocationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServer will
// result in compilation errors.
type UnsafeLocationServer interface {
	mustEmbedUnimplementedLocationServer()
}

func RegisterLocationServer(s grpc.ServiceRegistrar, srv LocationServer) {
	s.RegisterService(&Location_ServiceDesc, srv)
}

func _Location_SetUserLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).SetUserLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Location/SetUserLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).SetUserLocation(ctx, req.(*SetUserLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_ListUsersInRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersInRadiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).ListUsersInRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Location/ListUsersInRadius",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).ListUsersInRadius(ctx, req.(*ListUsersInRadiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Location_ServiceDesc is the grpc.ServiceDesc for Location service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Location_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Location",
	HandlerType: (*LocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUserLocation",
			Handler:    _Location_SetUserLocation_Handler,
		},
		{
			MethodName: "ListUsersInRadius",
			Handler:    _Location_ListUsersInRadius_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location.proto",
}
